apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: test-ns
  annotations:
    cert-manager.io/cluster-issuer: "my-ca-issuer"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - projekt.lab
    secretName: projekt-lab-tls
  rules:
  - host: projekt.lab
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
